name: Publish package to GitHub Packages
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/delete-package-versions@v3
        with:
          owner: 'dabogee'
          repo: 'com.dabogee.tools.simple-image-collage'
          package-name: 'com.dabogee.tools.simple-image-collage'
          token: ${{ secrets.ACCESS_TOKEN }}
          min-versions-to-keep: 1
          delete-only-pre-release-versions: "false"
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish package
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}